### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by ThatCuteOne** [lolouthefox/Sunshine#1]
After a game restart the settings dont save.
it gets all set back to default.

**Comment by lolouthefox** [comment]
Hi, yes this was an intended behavior, but I could add an option so you can choose to keep settings or not after restart

**Comment by lolouthefox** [comment]
Done!
I now use YACL which is easier to set up for my mod. You can now save and preview without having to quite the UI. [Checkout the full details on Modrinth](https://modrinth.com/mod/sunshine/version/1.1.0)
