### ISSUE TITLE
Toggle Hotkey

### ISSUE THREAD

**Issue by GhostIsBeHere** [lolouthefox/Sunshine#2]
Please add a hotkey so I can easily toggle between enabled and disabled.
Thank you!

**Comment by lolouthefox** [comment]
Sure, I'll add that!

**Comment by lolouthefox** [comment]
Done!
There now is a hotkey to toggle between frozen and unfrozen mod. [Checkout the full details on Modrinth](https://modrinth.com/mod/sunshine/version/1.1.0)
