### ISSUE TITLE
Sunshine complaining about yacl version no matter which installed.

### ISSUE THREAD

**Issue by neonod** [lolouthefox/Sunshine#4]
Seems the new version doesnt like the available version of yacl even when installing the version its specifically asking for. This was happening for both the 1.20 and 1.21.1 files for me.
![image](https://github.com/lolouthefox/Sunshine/assets/557031/bfeec37e-42dc-4f52-af55-eeed2faa2465)

Screenshot shows quite a few mods loaded but I also tried this with a blank list using just sunshine and the pre-reqs.

**Comment by lolouthefox** [comment]
That's odd, investigating rn

**Comment by lolouthefox** [comment]
Ok, fixed, look in an hour for updated versions on Modrinth
