### ISSUE TITLE
Minecraft won't launch

### ISSUE THREAD

**Issue by Maxtar07** [lolouthefox/Sunshine#6]
My game doesn't launch when I put on the sunshine mod.
I get a quilt error message telling me that sunshine needs "any version of yet_another_config_lib".
But I have "yet another config lib" in my mod folder.
[crash-2023-07-13_10.44.14.9175-quilt_loader.txt](https://github.com/lolouthefox/Sunshine/files/12037285/crash-2023-07-13_10.44.14.9175-quilt_loader.txt)

**Comment by lolouthefox** [comment]
Yeah, it's a problem with Fabric, I can't seem to find the issue, I'm working on it, sorry!

**Comment by lolouthefox** [comment]
Fixed and updated!

**Comment by Maxtar07** [comment]
perfect !
Suggestion : I don't know if it is possible, add an option to freeze the weather too.

**Comment by lolouthefox** [comment]
I know it is possible, but i couldn't make it work yet, but it should be coming someday
