### ISSUE TITLE
On 1.20.2 the config is not saved to the file

### ISSUE THREAD

**Issue by Rafii2198** [lolouthefox/Sunshine#7]
I tried to launch this mod on 1.20.2 but it was expecting exactly Minecraft 1.20.1, but I modified `fabric.mod.json` to change it to 1.20.2, and it works without any issues

**Comment by Rafii2198** [comment]
Actually, I dunno if I did something wrong, but after I closed the game second time (not the first) after changing the config, it got reset, which is pretty weird

**Comment by lolouthefox** [comment]
Hi, do you think you can make a pull request with the updated config files? Or you don't know how to do it, otherwise can you please send the changes you made, it would make it easier for me lol

**Comment by Rafii2198** [comment]
All I did was just changing the required Minecraft version from 1.20.1 to 1.20.2 but after playing for a bit, I noticed that configs just do not save no matter what you set there. Key thing is that it is not saving to the file, it actually reads, and the changes take effect in game but just the config file is not saved.
That makes the original issue wrong, I apologize, I should investigate it longer.

**Comment by Rafii2198** [comment]
I do not know much about coding, I am not a dev by any means, but I see that the mod is built for YACL for 3.0.3 while updates like 3.2.0 have made breaking changes. Update 3.2.0 is also the lowest possible version for 1.20.2, thus I can suspect that some stuff just do not work anymore.

**Comment by lolouthefox** [comment]
I'll be looking into it later in the next two weeks

**Comment by lolouthefox** [comment]
Still can't find any fix because YACL doesn't update their documentation...

**Comment by lolouthefox** [comment]
Fixed and v2 is out (not a lot of changes tho)
https://modrinth.com/mod/sunshine

I did not post any updates for 1.20.x, but that's as close as I could get from a resolution, tell me if it's still not saving
