### ISSUE TITLE
[Localization] Hardcoded about Freezing/Unfreezing the Time.

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [lolouthefox/Sunshine#8]
Hello!

I found that some Strings are hardcoded, so I decided to submit this Issue.

These messages don't appear in [`en_us.json`](https://github.com/lolouthefox/Sunshine/blob/master/src/main/resources/assets/sunshine/lang/en_us.json):
![image](https://github.com/lolouthefox/Sunshine/assets/51203385/7cb7d702-47c2-44ad-9e66-d787f7b3ae35)

Also I think that it can be changed in the [`Sunshine.java`](https://github.com/lolouthefox/Sunshine/blob/master/src/main/java/lolousstudio/sunshine/Sunshine.java) File.

**Comment by lolouthefox** [comment]
Thanks for reporting! Still can't figure out the new UI API anyway, so I won't update until a long time because nobody's helping haha

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> Thanks for reporting! Still can't figure out the new UI API anyway, so I won't update until a long time because nobody's helping haha

I'm still glad to see Your Answer, because any Answer is better than being ignored.

**Comment by lolouthefox** [comment]
Will be fixed in v2, hopefully solved a lot of issues i've had

**Comment by lolouthefox** [comment]
Fixed and v2 is out (not a lot of changes tho)
https://modrinth.com/mod/sunshine
